name: voice_chess_app
description: A voice-controlled chess game using the Gemini API.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.5
  provider: ^6.0.5
  speech_to_text: ^3.2.1
  flutter_chess_board: ^1.0.0
  http: ^0.14.0
  flutter_unity_widget: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
